### PR TITLE
Escape dollar characters in new examples.

### LINKED ISSUE #97: ReplaceExamples doesn't work properly if an example contains the dollar character.
The dollar character must be properly escaped in each example so that it isn't processed as a [substitution](https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions)

Can be tested by creating a function with the following example.

```powershell
"Input" | ForEach-Object {MyFunction -Parameter $_}
```

### PR DESCRIPTION
**Pull request by btimmerm**
Closes #97

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Thanks for the PR, really appreciated it.

I was about to respond to your ticket because there are a lot of test cases already using the `$` character in our [Get-Help examples fixture](https://raw.githubusercontent.com/alt3/Docusaurus.Powershell/master/Tests/Integration/CrossVersionCodeExamples.expected.mdx). Meaning I am not sure I fully understand which testcase this PR solves (yet).

I will try to look into it shortly.

**Comment by btimmerm** [comment]
Here is an example of a test that should pass.

````powershell
#Region: Build Test Environment
$ModuleName = "Issue97"
$ModulePath = "C:\Temp\Issue97"

If (-not (Test-Path -Path $ModulePath)) {
    [void](New-Item -Path $ModulePath -ItemType Directory -Force)
}

@'
Function Show-Issue97 {
    <#
        .SYNOPSIS
            SYNOPSIS
        .DESCRIPTION
            DESCRIPTION
        .EXAMPLE
            "Input" | ForEach-Object {Show-Issue97 -Name $_}
    #>
    Param(
        [string]$Name
    )

    Process {
        $Name
    }
}
'@ | Set-Content -Path "$($ModulePath)\$($ModuleName).psm1"
New-ModuleManifest -Path "$($ModulePath)\$($ModuleName).psd1" -ModuleVersion 1.0.0 -RootModule "$($ModuleName).psm1" -FunctionsToExport "Show-Issue97"
Import-Module -Name "$($ModulePath)\$($ModuleName).psd1"
#Get-help Show-Issue97 -Examples
#EndRegion: Build Test Environment

#Region: Test Issue97
Import-Module -Name PlatyPS, Alt3.Docusaurus.Powershell, Pester

$ExpectedResult = @'
---
id: Show-Issue97
title: Show-Issue97
hide_title: false
hide_table_of_contents: false
---

## SYNOPSIS

SYNOPSIS

## SYNTAX

```powershell
Show-Issue97 [[-Name] <String>]
```

## DESCRIPTION

DESCRIPTION

## EXAMPLES

### EXAMPLE 1

```powershell
"Input" | ForEach-Object {Show-Issue97 -Name $_}
```

## PARAMETERS

### -Name

{{ Fill Name Description }}

```yaml
Type: String
Parameter Sets: (All)
Aliases:

Required: False
Position: 1
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```

## INPUTS

## OUTPUTS

## NOTES

## RELATED LINKS

'@

New-DocusaurusHelp -Module "$($ModulePath)\$($ModuleName).psd1" -DocsFolder "$($ModulePath)\docs"
$Result = Get-Content "$($ModulePath)\docs\commands\show-Issue97.mdx" -Raw

$Result | Should -Be $ExpectedResult
#EndRegion: Test Issue97
````

**Comment by bravo-kernel** [comment]
Thanks for the test. Please know that I am not ghosting this ticket. Vacation came in the way, no working on fixing my local tests.

💯

**Comment by bravo-kernel** [comment]
Hi there, I have fixed the CI pipeline. Could you please rebase to master so it (hopefully) triggers the test suite?

**Comment by bravo-kernel** [comment]
Thank you kindly for this fix sir, took some time to fix the pipeline but was due anyway. Much much appreciated 💯.

If you are using this for a website let me know and I will add it to the readme.

**Pull request merged**
